name: Tokens
on:
  push:
    paths:
    - 'tokens/**'
defaults:
  run:
    working-directory: tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json build/tokens.json
      # Convert tokens according to Style Dictionary config
      - run: npx style-dictionary build --config config.json
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update tokens
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
